name: messagyre_client
description: "Gymnase de Renens' private messaging and personal agenda app."
publish_to: "none"

version: 1.28.420+420
# 1.0   Initial release
# 1.1   Added Settings page
# 1.2   Added Homework page
# 1.3   Added Grades page
# 1.4   Automatic login
# 1.5   Added profile pictures
# 1.6   Added profile page
# 1.7   Revamped Grades page
# 1.8   Added notifications
# 1.9   Added read receipts
# 1.10  Improved chat and chats page graphics
# 1.11  Build for iOS devices
# 1.12  Added custom navigation bar and improved UI
# 1.13  Revamped homework system
# 1.14  All pages redesign + Added DisplayName
# 1.15  Added custom wallpapers, changed pickers, improved UI/UX
# 1.16  Added iOS notifications
# 1.17  Homework page major upgrade
# 1.18  Added chat messages options (focusing)
# 1.19  Added a reset password option
# 1.20  Added chat banner
# 1.21  Added EULA requirements
# 1.22  Added homework page searchbar and tags
# 1.23  Increased possible grade weights
# 1.24  Added a grade display to the new grade page
# 1.25  Added incoming grades from the homework page
# 1.26  Implemented device calendar syncronization with the app's homework
# 1.27  Support can now be contacted from the settings page
# 1.28  Added local data backup options

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  settings_ui: ^2.0.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  http: ^1.5.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  flutter_secure_storage: ^10.0.0-beta.4
  collection: ^1.17.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.7.0
  package_info_plus: ^9.0.0
  modal_bottom_sheet: ^3.0.0
  uuid: ^4.5.1
  flutter_keyboard_visibility: ^6.0.0
  fl_chart: ^1.1.1
  custom_navigation_bar: ^0.8.2
  easy_date_timeline: ^2.0.9
  dotted_border: ^3.1.0
  hugeicons: ^1.1.0
  animated_line_through: ^1.0.5
  loading_animation_widget: ^1.3.0
  image_cropper: ^11.0.0
  keyboard_actions: ^4.2.0
  flutter_html: ^3.0.0
  flutter_phoenix: ^1.1.1
  flutter_confetti: ^0.5.1
  flutter_local_notifications: 18.0.1
  image: ^4.5.4
  path_provider: ^2.1.5
  flutter_app_badger: ^1.5.0
  device_calendar: ^4.3.3
  archive: ^4.0.7
  file_picker: ^10.3.7
  shimmer_animation: ^2.2.2+1
  flutter_dash: ^1.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: "assets/icons/full.png"           # Generic Icon
  image_path: "assets/icons/full-christmas.png"   # Christmas Icon

flutter_native_splash:
  android: true
  ios: true

  image: assets/icons/purple.png
  image_dark: assets/icons/white.png
  
  color: "#ffffff"
  color_dark: "#000000"

  android_gravity: center

  