platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  pod 'FirebaseCore', '~> 10.15'
  pod 'FirebaseFirestore', '~> 10.15'
  pod 'FirebaseAuth', '~> 10.15'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Forza deployment target a iOS 15
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      # Fix TOOLCHAIN_DIR
      xcconfig_path = config.base_configuration_reference.real_path
      text = File.read(xcconfig_path)
      text.gsub!("${DT_TOOLCHAIN_DIR}", "$(TOOLCHAIN_DIR)")
      File.open(xcconfig_path, "w") { |file| file.puts text }

      # Forza C++17 e libc++
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

      # Patch workaround per gRPC-Core: disabilita aligned new/delete per Xcode 15+
      if target.name.start_with?('gRPC-Core')
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DGRPC_NO_ALIGNED_ALLOC'
      end
    end

    # Fix per BoringSSL-GRPC (rimuoviamo flag problematici)
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
