platform :ios, '15.0'

use_frameworks!
use_modular_headers!

pod 'FirebaseCore', :modular_headers => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
end
